[package]
name = "postman-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
