[focus]
foreground = 0x007AB2D3
background = 0x0037AFE1
highlight = 0x00DFF2EB
border  = 0x004CC9FE

[normal]
foreground = 0x007AB2D3
background = 0x0037AFE1
highlight = 0x00DFF2EB
border  = 0x004CC9FE
